export function createDefaultConfig() {
  return {
    entry: "./src/main.bca",
    srcDir: "./src",
    outDir: "./dist",
    project: {
      slug: "bedrock-addon",
      namespace: "bedrock",
      version: [1, 0, 0],
      target: "1.21.100"
    },
    packs: {
      behavior: {
        name: "Behavior Pack",
        description: "Generated by bedrockc"
      },
      resource: {
        name: "Resource Pack",
        description: "Generated by bedrockc"
      }
    },
    scripts: {
      enabled: false,
      modules: []
    }
  };
}
